name: feeling-finder
grade: stable
adopt-info: feeling-finder
summary: A fast and beautiful emoji picker.
description: |
  Fast and beautiful emoji picker. Easily find the perfect emoji by genre.
base: core22
confinement: strict
compression: lzo
architectures:
  - build-on: amd64
    build-for: amd64
  
apps:
  feeling-finder:
    command: feeling_finder
    extensions: [gnome]
    common-id: codes.merritt.FeelingFinder
  
parts:
  feeling-finder:
    plugin: dump
    source: https://github.com/Merrit/feeling_finder/releases/download/v1.1.0/FeelingFinder-Linux-Portable.tar.gz 
    
