name: feeling-finder
grade: stable
version: 1.0.0
summary: A fast and beautiful emoji picker.
description: |
  Fast and beautiful emoji picker. Easily find the perfect emoji by genre or search.
base: core22
confinement: strict
compression: lzo
architectures:
  - build-on: amd64
    build-for: amd64
  
apps:
  feeling-finder:
    command: feeling_finder
    extensions: [gnome]
    plugs:
      - home
      - network
      - optical-drive
      - removable-media
    common-id: codes.merritt.FeelingFinder
  
parts:
  feeling-finder:
    plugin: dump
    source: https://github.com/Merrit/feeling_finder/releases/download/v1.0.0/FeelingFinder-Linux-Portable.tar.gz
    #build-packages:
      #- curl
      #- build-essential
      #- wget
    #override-pull: |
      #craftctl default
      #craftctl set version=$(git describe --tags --abbrev=0 | cut -c 2-)
      #VER="$(git describe --tags --abbrev=0 | cut -c 2-)"
      #wget -q -O- https://github.com/Merrit/feeling_finder/releases/download/v${VER}/FeelingFinder-Linux-Portable.tar.gz |\
           #tar xf - --strip-components=1 -C $CRAFT_PART_SRC
    
    #https://github.com/Merrit/feeling_finder/releases/download/v1.0.0/FeelingFinder-Linux-Portable.tar.gz  

