name: feeling-finder
grade: stable
adopt-info: feeling-finder
summary: A fast and beautiful emoji picker.
description: |
  Fast and beautiful emoji picker. Easily find the perfect emoji by genre.
base: core22
confinement: strict
compression: lzo
architectures:
  - build-on: amd64
    build-for: amd64
  
apps:
  feeling-finder:
    command: feeling_finder
    extensions: [gnome]
    common-id: codes.merritt.FeelingFinder
  
parts:
  feeling-finder:
    plugin: dump
    source: https://github.com/Merrit/feeling_finder.git 
    build-packages:
      - build-essential
      - curl
    override-pull: |
      craftctl default
      craftctl set version=$(git describe --tags --abbrev=0 | cut -c 2-)
      VER="$(git describe --tags --abbrev=0 | cut -c 2-)"
      wget -q -O- https://github.com/Merrit/feeling_finder/releases/download/v${VER}/FeelingFinder-Linux-Portable.tar.gz |\
           tar –xvzf FeelingFinder-Linux-Portable.tar.gz –C $CRAFT_PART_SRC     
    
  cleanup:
    plugin: nil
    after: [feeling-finder]
    override-prime: |
      craftctl default
      rm -f FeelingFinder-Linux-Portable.tar.gz
      
