name: feeling-finder
grade: stable
adopt-info: feeling-finder
summary: A fast and beautiful emoji picker.
description: |
  Fast and beautiful emoji picker. Easily find the perfect emoji by genre or search.
base: core22
confinement: strict
compression: lzo
architectures:
  - build-on: amd64
    build-for: amd64
  

apps:
  feeling-finder:
    command: feeling_finder
    extensions: [gnome]
    plugs:
      - home
      - network
      - optical-drive
      - removable-media
    common-id: codes.merritt.FeelingFinder
  #desktop: usr/share/applications/.desktop

parts:
  feeling-finder:
    plugin: flutter
    source: https://github.com/Merrit/feeling_finder.git
    build-packages:
      - curl
      - build-essential
    override-build: |
      craftctl default
      craftctl set version=$(git describe --tags --abbrev=0)
    #chmod a+x ./
    #stage-packages:
      #- libjsoncpp25
    
    
      
  
      

